server:
  port: 8093

spring:
  application:
    name: service-ai
  config:
    import: optional:nacos:service-ai.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
