server:
  port: 8094

spring:
  application:
    name: service-iot
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mqtt:
  broker-url: tcp://localhost:1883
  client-id: iot-service
  topics:
    - elder/+/+/+/up/+
  qos:
    - 1