server:
  port: 8091

spring:
  application:
    name: service-vital
  config:
    import: optional:nacos:service-vital.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
